### ISSUE TITLE
Agregar el user.serialize al response_body

### ISSUE THREAD

**Issue by hchocobar** [4GeeksAcademy/sp65-final-project-g3#45]
# route.py

Agregar user.serialize() al retornar el body

* En el endpoint `/signup` entre la línea 79 y 80, agregar `response_body['results'] = user.serialize()`

![imagen](https://github.com/4GeeksAcademy/sp65-final-project-g3/assets/45291267/b4415054-c489-4ed1-91e0-2710c609b8eb)

* En el endpoint `/login` entre la línea 92 y 93, agregar `response_body['results'] = user.serialize()`

![imagen](https://github.com/4GeeksAcademy/sp65-final-project-g3/assets/45291267/06134a6e-0fc0-41f6-98de-f100522e8745)

**Comment by kamelmat** [comment]
Listo Hector, Gracias
